### ISSUE TITLE
oroMemset is not working properly

### ISSUE THREAD

**Issue by meistdan** [amdadvtech/Orochi#75]
Function `oroMemset` is not working properly:
```
oroError OROAPI oroMemset(oroDeviceptr dstDevice, unsigned int ui, size_t N)
{
	__ORO_FUNC1( MemsetD32( (CUdeviceptr)dstDevice, ui, N/sizeof(int) ), MemsetD32( dstDevice, ui, N / sizeof(int) ) );
	return oroErrorUnknown;
}
```
For example, if I want to set `1` with size 4, it sets only the firtst byte to `1` and others are `0`s. Also, if the the input is not aligned to 4 bytes, then the remaining bytes are untouched.

**Comment by KaoCC** [comment]
Note that `cuMemsetD32` needs to be 4-byte aligned as written in the [spec](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1g983e8d8759acd1b64326317481fbf132).
If you need to deal with non-aligned data, the best option might be `Memcpy`

**Comment by RichardGe** [comment]
In Orochi 2.0,
oroMemset is bound to hipMemset/cudaMemset
oroMemsetD32 is bound to hipMemsetD32/cuMemsetD32

That should be more clear, and resolve this issue.
