### ISSUE TITLE
Radix sort baked version is not working

### ISSUE THREAD

**Issue by meistdan** [amdadvtech/Orochi#77]
Radix sort baked version is not working (a couple of compilation errors) due to recent changes in the code: https://github.com/amdadvtech/Orochi/blob/main/ParallelPrimitives/RadixSort.cpp#L156

**Comment by meistdan** [comment]
@KaoCC Could you check this one please? It was reported by CQE.

**Comment by KaoCC** [comment]
Fixed in #79
