### ISSUE TITLE
hiprtc_paths is never closed

### ISSUE THREAD

**Issue by KaoCC** [amdadvtech/Orochi#81]
`hiprtc_paths` in hipew is loaded with `dynamic_library_open_find` but is never released when the program exit.

This might create a problem where some of the dlls are occupied by the processes that are in "exit state".

**Comment by RichardGe** [comment]
just fixed in the main branch of GPUOpen-LibrariesAndSDKs
https://github.com/GPUOpen-LibrariesAndSDKs/Orochi/commit/d40b1194ae6b7c3a667f3a20e8a25e9e7b2669f5
