### ISSUE TITLE
Add const qualifier for void** in oroModuleLaunchKernel

### ISSUE THREAD

**Issue by yusuke-tokuyoshi** [amdadvtech/Orochi#97]
https://github.com/amdadvtech/Orochi/blob/c10d59211444a36d4f336ad721928d425fadea8b/Orochi/Orochi.h#L994
Can we add `const` to void** as follows?
```
oroError_t OROAPI oroModuleLaunchKernel(oroFunction_t f, unsigned int gridDimX, unsigned int gridDimY, unsigned int gridDimZ, unsigned int blockDimX, unsigned int blockDimY, unsigned int blockDimZ, unsigned int sharedMemBytes, oroStream_t stream, const void *const * kernelParams, const void *const * extra);
```
I think this change allows us to input const-qualified parameters to `oroModuleLaunchKernel`.

**Comment by takahiroharada** [comment]
Yes we need to add. I realized this too.

**Comment by KaoCC** [comment]
I posted to here :
https://github.com/GPUOpen-LibrariesAndSDKs/Orochi/issues/110
