### ISSUE TITLE
Use std::filesysytem to remove deplicated std::codecvt_utf8_utf16

### ISSUE THREAD

**Issue by yusuke-tokuyoshi** [amdadvtech/Orochi#99]
`std::codecvt_utf8_utf16`, that has security flaw and officially deprecated, is used in `utf8_to_wstring`.
https://github.com/GPUOpen-LibrariesAndSDKs/Orochi/blob/e8da229ac37877e431ca5a512db17246992dcd6b/Orochi/OrochiUtils.cpp#L39

`utf8_to_wstring` is used for paths. Therefore, we can replace these path types with `std::filesystem` that handles character encoding.

**Comment by KaoCC** [comment]
This repo is archived. Could you create an issue in 
[GPUOpen-LibrariesAndSDKs/Orochi](https://github.com/GPUOpen-LibrariesAndSDKs/Orochi)  ?

**Comment by yusuke-tokuyoshi** [comment]
This was just memorandum for @shoikeda, and I don't want to post the code of RTB which is not public. But you can maintain Orochi, I'll recreate issues in public one with removing RTB code etc.
